### ISSUE TITLE
Game "hangs" and takes all cpu it can get

### ISSUE THREAD

**Issue by GoogleCodeExporter** [infidel-/cult#27]
```
Game stops responding and goes to 100% CPU. I noticed it happens when "End 
turn" tooltip shows up.
I'm on Chromium 7.0.517.44 (64615) Ubuntu 10.04. Flash is disabled with Flash 
Block.
```

Original issue reported on code.google.com by `DOzminkowski` on 20 Nov 2010 at 11:12

Attachments:
* [screenshot.png](https://storage.googleapis.com/google-code-attachments/cult/issue-27/comment-0/screenshot.png)

**Comment by Prof-hu** [comment]
Does this project have any life in it? I tend to come back to this game regularly, and this issue keeps me from finishing games quite often. I can see that there are some suggestions to fix it, sad that it was not put there as a pull request actually. Would it help if I would create one with these suggestions? I have some concerns though, like "stealing" the code from someone else, and also if there's any point... (Could a fix be deployed to the game website in the and at all...)

**Comment by infidel-** [comment]
Well, if you report a bug I will try to fix it, other than that no actual work is going on. I wonder how I missed that one with the issue open and all. Probably marked as read in my inbox accidentally. I will look into it.

> sad that it was not put there as a pull request actually.
This issue is an export from Google Code and pull requests are a Github thingy.

> Would it help if I would create one with these suggestions? I have some concerns though, like "stealing" the code from someone else, and also if there's any point... (Could a fix be deployed to the game website in the end at all...)

No need to create another issue. As for your concerns, sure, if I can fix it, it will be deployed, don't worry :)

**Comment by Prof-hu** [comment]
Oh, I presumed that this project is mostly forgotten considering the very little activity seen here. I'm delighted to find out that I was wrong. :)
I haven't used Google Code, sorry for my misunderstanding.
I would be very grateful for a fix on this issue. (Recently it annoyed me enough to find the same part of code in the browser debug console, and I managed to kick it out from the infinite loop by changing a value taking part in the condition that kept it in the loop. That's when I checked how I could get in touch and ask for a fix. :)

**Comment by Prof-hu** [comment]
BTW, I saw that you have google analytics code built-in. What do the numbers show? Is there anyone else playing with the game anymore apart from me? :)

**Comment by infidel-** [comment]
I rarely look at it. But, surprisingly, a couple hundred people do play it.

**Comment by infidel-** [comment]
v5.2 is up with the proposed fix! Please, test it and see if everything is fine.

**Comment by Prof-hu** [comment]
> v5.2 is up with the proposed fix! Please, test it and see if everything is fine.
Thanks @infidel- , I haven't had a lot of opportunities to test, and also it is hard to reproduce (it happens by chance), but so far no infinite loops. :)

**Comment by infidel-** [comment]
Great, I'll keep the issue up for a couple of weeks in case there are more similar problems.
