### ISSUE TITLE
HTML5 music player

### ISSUE THREAD

**Issue by GoogleCodeExporter** [infidel-/cult#39]
```
1
```

Original issue reported on code.google.com by `starinfi...@gmail.com` on 24 Oct 2011 at 9:32

**Comment by techtonik** [comment]
Upgrading https://github.com/scottschiller/SoundManager2 should do the trick.

**Comment by infidel-** [comment]
Thanks, I'll check this out when I have the time.

**Comment by infidel-** [comment]
Seems to be a little buggy in Firefox but oh, well.

**Comment by techtonik** [comment]
Works for me in FF. Thanks. )

**Comment by infidel-** [comment]
Do the pause/stop buttons work correctly? And which OS are you on?

**Comment by techtonik** [comment]
Well, when I hit Play multiple times it becomes broken. I guess the check or callback that audio is already playing is broken.

**Comment by infidel-** [comment]
Sheesh, it was actually a six year old bug. It never occured to me to push play button multiple times or maybe the Flash library handled that :)

Fixed.

**Comment by techtonik** [comment]
Probably it was some ancient bug in SoundManager that Flash library didn't support multiple streams. 8a28e9c2
