### ISSUE TITLE
Haxe 3

### ISSUE THREAD

**Issue by techtonik** [infidel-/cult#49]
There are some helpers that can leave less work to do http://old.haxe.org/manual/haxe3/migration

**Comment by infidel-** [comment]
Well, there's not much point. The development has stopped a long time ago apart from bugfixes or compatibility changes if necessary.

**Comment by techtonik** [comment]
The game looks complete and I doubt it needs more features. Maybe less? But being able to experiment with it using default tools could still be fun.

**Comment by infidel-** [comment]
When you put it this way, there's some value in that. I vaguely recall that when I tried it last time, I've stumbled on some things that were too much hassle to fix but I'll give it one more try.

**Comment by techtonik** [comment]
The whole ecosystem around Haxe seems more matures since 2 times with tools such as https://github.com/openfl

**Comment by infidel-** [comment]
Well, it took a few hours to get it working and then a couple more to make it a bit tidier than before.

**Comment by techtonik** [comment]
Nice. Works fine in FF without any console warnings.
