### ISSUE TITLE
Play page not available

### ISSUE THREAD

**Issue by Trilarion** [infidel-/cult#56]
http://www.in-fi-del.net/static/cult/index.html delivers a "404 Site not found" message currently.

**Comment by infidel-** [comment]
I've changed the domain and forgot to fix the README:
https://www.infidel.rocks/static/cult/index.html

**Comment by Trilarion** [comment]
Thanks Old link is also on the Github page's about section (top right).

**Comment by infidel-** [comment]
Fixed. Cheers!
